name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: rustup toolchain install nightly
    - name: setup2
      run: rustup default nightly
    - name: Build
      run: cargo install --path gameserver
    - name: Run tests
      run: cargo install --path sdkserver
